
services:
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - dind-storage:/var/lib/docker
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
    command: ["--storage-driver=overlay2"]
    networks: 
      jenkins:
        aliases: [docker]

networks:
  jenkins: {}

volumes:
  dind-storage:
  docker-certs-ca:
  docker-certs-client:

